sudo: required
dist: trusty
language: node_js
node_js:
  - "8"
install:
  - npm install -g truffle
  - npm install -g ethereumjs-testrpc
  - npm install --save-dev solidity-coverage
  - npm install
before_script:
  - npm run gana
  - sleep 5
script:
  # - truffle test
after_script:
  - npm run coverage